INSERT INTO FIRM(ID, NAME) VALUES (1, "AGRINES");
INSERT INTO FARM(ID, NAME, NOTE, FIRM_ID) VALUES (1, "GRANJA DA HORA", "GRANJA MUITO LEGAL", 1);
INSERT INTO ANIMAL_GROUP (ID, NAME, SITUATION, FARM_ID) VALUES (1, "LOTE DE PORQUINHOS", "C", 1);

